apiVersion: v1
kind: Service
metadata:
  name: default-backend
  labels:
    component: default-backend
spec:
  selector:
    component: default-backend
  ports:
    - port: 8080
      targetPort: 8080
